---
title: "Weight of Fish"
author: "Kathleen Castro"
date: "`r Sys.Date()`"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
```

# Predicting Fish Weight

```{r}
Fish <-read.csv(file="Fish.csv",header=TRUE)
```


## Perch

```{r}
Perch <- filter(Fish, Species== "Perch")
Perch <- select(Perch, -(Species))
```

### Best Models

```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ .,
               data = Perch,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")
```

### Best Two regressor model
  
```{r}
best.model <- lm(Weight~Height+Width,data=Perch)
summary(best.model)
```
  
Both the best model and best two regressor model give a similar data outcome set.

## Pike

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements